---

certbot_pkg_name: certbot

certbot_pip_depends:
      - python
      - python-dev
      - python-virtualenv
      - gcc
      - dialog
      - libaugeas0
      - libssl-dev
      - libffi-dev
      - ca-certificates
      - python-pip
      - git
